### ISSUE TITLE
Keyboard Corruption

### ISSUE THREAD

**Issue by tgmaxx** [MiSTer-devel/ao486_MiSTer#101]
The core ao486_20220224.rbf causes keyboard (wired or wireless) to be corrupted, making it impossible to use the core. Some keys do nothing, most keys show wrong characters and enter key does nothing.

**Comment by Rumbledethumps** [comment]
You need to update the BIOS manually. None of the automatic update scripts worked for me.

**Comment by tgmaxx** [comment]
I tried several BIOS versions, but that made no difference.  If I use the previous release of the core (20220211), it works.

**Comment by Rumbledethumps** [comment]
I needed this one for 20220224. I also found it was loading an old one from a USB stick. Maybe you're hitting more layers too, but you definitely need this new BIOS.
https://github.com/MiSTer-devel/ao486_MiSTer/commit/5e0199a09c2b7ac0b326d30f2d2f360b74301ca3

**Comment by sorgelig** [comment]
it's not a real issue but partial update.

**Comment by sorgelig** [comment]
update script DOES NOT update bios (boot0.rom) if it exists. You have to remove boot0.rom manually and then run script again.
Problem wouldn't exist if users would START to read what script writes on screen.

**Comment by Rumbledethumps** [comment]
I removed boot0.rom and ran update.sh. It did not do anything useful. Running update_all.sh does grab a fresh bios but nothing useful was printed to the screen. What did print to the screen scrolled away pretty quick. I looked at the log and script sources and didn't see anything helpful either.

I understand you think the the needed information is being properly presented to the users, but it is not. That is the issue here. If a technical approach is not being considered at this time, just say so and I'll PR the readme.
