### ISSUE TITLE
Tie Fighter CD Joystick buttons not responding

### ISSUE THREAD

**Issue by Chris5523** [MiSTer-devel/ao486_MiSTer#30]
After the update from August 16th 2020 the Joystick is finally detected in Tie Fighter CD but it isn't responding to any button press. It works fine in X-Wing and Tie Figher.

**Comment by Jayde6** [comment]
Adding this here rather than starting a new Issue for the same kind of problem, the same goes for the game Backroad Racers, detects joystick but no way to make it through calibration as it doesn't detect any input. Other games work fine. The game will also detect a joystick when none are turned on (Bluetooth).

**Comment by vpelletier** [comment]
As of release 2021/02/26, with a PS3 controller in bluetooth, with Tie Fighter (1995 DOS CD as of GoG: rename `game.ins` as `game.cue`, and copy `game.gog` along with it):
- 2-buttons joystick mode: no button press is detected
- 4-buttons joystick mode: triangle and square are detected, left stick does something but calibration does not work properly
- gravis pro mode: seems to be spamming some button (not sure which, and may be inherent to this controller model)

Microprose Formula 1 Grand Prix, though, is happy with both 2- and 4-buttons modes. Direction arrows may need to be pressed before the left stick works.

**Comment by vpelletier** [comment]
> - 2-buttons joystick mode: no button press is detected
> - 4-buttons joystick mode: triangle and square are detected

Both these points together actually mean Tie Fighter is using input from the second joystick for some reason.

> , left stick does something but calibration does not work properly

This is because the axis encoding is broken: analog-to-digital axis conversion is implemented by going through a duration (probably a ramp ADC) which is supposed to go from 24us to 1124us on perfectly calibrated sticks. But using Henrik K. Jensen's Joystick Tester under FreeDOS 1.3rc4 with ao486 at 90MHz, the whole range is 20 to 284. Why did I specify the frequency ? Because the joystick emulation uses a fixed number of clock cycles when converting from input to delay, while it should depend on the input frequency. I have a tentative patch, but quartus being a pain (failing to fit the design on the chip, which I do not thing it should be related to my change: I only use 23 more register bits and a single 2-entries LUT).

> - gravis pro mode: seems to be spamming some button (not sure which, and may be inherent to this controller model)

Gravis pro is sending digital data over the joystick port instead of analog, so of course it will be doing garbage for any program which does not expect it.

**Comment by sorgelig** [comment]
it's more complicated than you may think. Analog joystick is not reliable even on real HW - that's why many games request calibration on start.
You can change SEED value if quartus fails on compilation. Sometimes it happens.

**Comment by vpelletier** [comment]
> Analog joystick is not reliable even on real HW

It is indeed not reliable, because of imprecisions in the potentiometers and the ADC. Both of which are digital in this case (at least for what the core sees, anyway). But either way, this is not my point: the current code uses a fraction of the available range when at 90MHz and 56.25MHz, and exceeds the maximum sampling delay at 30MHz and 15MHz. The former means the accuracy port-calibration is a reduced a lot (by a rough factor 5), and the latter means there are dead zones in the bottom and right.

I also suspect (but will need to get a working build to confirm this) that Tie Fighter is switching to joystick 2 instead of 1 because it sees the joystick being off-center. Alternatively, it could be because the emulation provides anything at all which is not a timeout even when there is no second controller available.

Also, after understanding the significance of buttons 3 & 4 being detected by Tie Fighter (and not 1 & 2), I could confirm that calibration succeeds with the second joystick.

Finally, and on a very tangential note, while reading the code I noticed the joystick code has a massive dead zone (60 on both ends, so 120 out of 256 values, so roughly half of the available angles come up as a centered stick). I'm very surprised by this, and I think it should be reduced, but I do not have experience with a lot of sticks so I do not know if reducing the deadzone would be welcome, or if it would cause annoyance on not-ideal hardware.

**Comment by rsn8887** [comment]
I also noticed this problem and I found a temporary workaround. You can use the mouse to control the menus. Once you are in a mission, in the 3D engine, you can press "ALT+C" to bring up the in-game calibration screen. In that screen, I can successfully calibrate using 2-button Joystick. Then, I can fly using the left analog stick on my PSX controller connected to MiSTer.
