### ISSUE TITLE
Windows NT IDE failure

### ISSUE THREAD

**Issue by iMartyn** [MiSTer-devel/ao486_MiSTer#70]
Low priority I know, but Windows NT 3.51 should be within spec for ao486.

It is currently impossible to install though as immediately after the kernel boots (Disk 2 of the boot disks), you get a kernel stop with INACCESSIBLE_BOOT_DEVICE

From what has been pieced together this is _probably_ something to do with the IDE controller handing off to the VHD handler.  It's kinda tricky to debug but happy to help test things.

**Comment by Doridian** [comment]
The IDE controller in general seems to be .... barebones.
I have been (for the fun of it) trying to get slackware linux 7.1 to run, however whenever it writes to the HDD, those write go very slow.
I can fdisk the disk (takes like 5 minutes to just save the partition table)
But mke2fs (formatting) just gets stuck mid-way and doesn't move any further.
I assume this is because Linux uses direct access to the IDE controller and not BIOS routines like DOS/Win95/98 do (INT 13h)
I get some drive errors when the live ISO of Linux boots already, so that further strenghtens my suspicion in this direction.
Also even in Win98 the drive controller shows as error (but still works due to the BIOS routine fallback)

**Comment by wishusknight** [comment]
It is basically implemented well enough to perform what the core is intended to do. Dos gaming.  I know this sounds rather glib, but that is the truth of it lol. 

It does seem like some people working on it though do want to improve it beyond this scope and are starting to. So it really is only a matter of time. It just may take a while.  Until then if stuff like NT and Linux work, it is just dessert after dinner, but not a bug if it doesn't.

**Comment by sajattack** [comment]
Jumping on the pile, I've also experienced some ide errors trying to run Gentoo Linux. https://misterfpga.org/viewtopic.php?f=13&t=4006

**Comment by sorgelig** [comment]
it's supposed to be fixed already. WinNT works now.
